repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: check-merge-conflict
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: trailing-whitespace

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.26.0
  hooks:
  - id: markdownlint

- repo: https://github.com/AleksaC/hadolint-py
  rev: v1.19.0
  hooks:
  - id: hadolint
    args: [--ignore, DL3008]
