name: Publish CI Docker image
on:
  push:
    paths:
      - '*.Dockerfile'
      - '.github/workflows/docker-build.yml'
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3


      - name: Install Python
        uses: actions/setup-python@v4
      - name: Lint
        uses: pre-commit/action@v3.0.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Ubuntu Qt6
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./ubuntu-qt6.Dockerfile
          push: true
          tags: ghcr.io/derpicated/articated-ci-qt6:latest
