name: Publish CI Docker image
on:
  push:
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-build.yml'
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2


      - name: Install Python
        uses: actions/setup-python@v2
      - name: Lint
        uses: pre-commit/action@v2.0.3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Ubuntu Qt5
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./ubuntu-qt5.Dockerfile
          push: true
          tags: ghcr.io/derpicated/articated-ci-qt5:latest

      - name: Build and push Fedora Qt6
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./fedora-qt6.Dockerfile
          push: true
          tags: ghcr.io/derpicated/articated-ci-qt6:latest
